[2016-05-07 23:12:33] request.INFO: Matched route "homepage". {"route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8081/my_project/web/"} []
[2016-05-07 23:12:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-05-07 23:12:33] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Unable to create the cache directory (C:\xampp\htdocs\my_project\app\cache\prod/twig/64)." at C:\xampp\htdocs\my_project\vendor\twig\twig\lib\Twig\Cache\Filesystem.php line 60 {"exception":"[object] (RuntimeException(code: 0): Unable to create the cache directory (C:\\xampp\\htdocs\\my_project\\app\\cache\\prod/twig/64). at C:\\xampp\\htdocs\\my_project\\vendor\\twig\\twig\\lib\\Twig\\Cache\\Filesystem.php:60)"} []
[2016-05-08 17:58:17] request.INFO: Matched route "homepage". {"route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8081/phpsymfonytest/web/"} []
[2016-05-08 17:58:17] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2016-05-08 17:58:17] request.CRITICAL: Uncaught PHP Exception RuntimeException: "There is no user provider for user "AppBundle\Entity\User"." at C:\xampp\htdocs\phpsymfonytest\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ContextListener.php line 174 {"exception":"[object] (RuntimeException(code: 0): There is no user provider for user \"AppBundle\\Entity\\User\". at C:\\xampp\\htdocs\\phpsymfonytest\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ContextListener.php:174)"} []
[2016-05-08 19:44:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /register"" at C:\xampp\htdocs\phpsymfonytest\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /register\" at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-05-08 21:27:19] request.INFO: Matched route "homepage". {"route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8081/phpsymfonytest/web/"} []
[2016-05-08 21:27:20] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2016-05-08 21:27:20] request.CRITICAL: Uncaught PHP Exception RuntimeException: "There is no user provider for user "AppBundle\Entity\User"." at C:\xampp\htdocs\phpsymfonytest\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ContextListener.php line 174 {"exception":"[object] (RuntimeException(code: 0): There is no user provider for user \"AppBundle\\Entity\\User\". at C:\\xampp\\htdocs\\phpsymfonytest\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ContextListener.php:174)"} []
[2016-05-11 11:25:25] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /information"" at C:\xampp\htdocs\phpsymfonytest\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /information\" at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-05-11 11:25:35] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /information"" at C:\xampp\htdocs\phpsymfonytest\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /information\" at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-05-11 12:27:25] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login"" at C:\xampp\htdocs\phpsymfonytest\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-05-11 12:27:54] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /information"" at C:\xampp\htdocs\phpsymfonytest\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /information\" at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-05-11 12:48:56] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /app_dev.app/information"" at C:\xampp\htdocs\phpsymfonytest\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /app_dev.app/information\" at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-05-11 12:49:52] request.INFO: Matched route "homepage". {"route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8081/phpsymfonytest/web/"} []
[2016-05-11 12:49:52] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2016-05-11 12:49:52] request.CRITICAL: Uncaught PHP Exception RuntimeException: "There is no user provider for user "AppBundle\Entity\User"." at C:\xampp\htdocs\phpsymfonytest\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ContextListener.php line 174 {"exception":"[object] (RuntimeException(code: 0): There is no user provider for user \"AppBundle\\Entity\\User\". at C:\\xampp\\htdocs\\phpsymfonytest\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ContextListener.php:174)"} []
[2016-05-11 14:54:03] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /information"" at C:\xampp\htdocs\phpsymfonytest\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /information\" at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-05-11 22:15:53] request.INFO: Matched route "homepage". {"route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8081/phpsymfonytest/web/"} []
[2016-05-11 22:15:53] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2016-05-11 22:15:53] request.CRITICAL: Uncaught PHP Exception RuntimeException: "There is no user provider for user "AppBundle\Entity\User"." at C:\xampp\htdocs\phpsymfonytest\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ContextListener.php line 174 {"exception":"[object] (RuntimeException(code: 0): There is no user provider for user \"AppBundle\\Entity\\User\". at C:\\xampp\\htdocs\\phpsymfonytest\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ContextListener.php:174)"} []
[2016-05-17 17:03:39] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /app_dev.ph"" at C:\xampp\htdocs\phpsymfonytest\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /app_dev.ph\" at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\phpsymfonytest\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
